#!/usr/bin/env bash
cd ..
make
cd test
cp ../encode a.out

# Ensure that test_huffman_code() is uncommented in encode.c and
# no other text is printed to stdout

# Also ensure that the the expected huffman codes have been 
# generated by uncommenting print_expected_huffman_code() in 
# encode.c and saving the output from that to a test file in 
# the huffman_code_exp folder
for i in {1..5}
do
    ./a.out infiles/test$i.txt > huffman_code_out/test$i.txt
    DIFF=$(diff huffman_code_out/test$i.txt huffman_code_exp/test$i.txt) 
    if [ "$DIFF" != "" ] 
    then
        echo "TEST $i FAILED" 
        echo "$DIFF"
        echo ""
    else
        echo "TEST $i PASSED" 
    fi
done

rm a.out
